package com.yj.widget

internal enum class WidgetAction {
    ACTION_START,
    ACTION_RESUME,
    ACTION_PAUESE,
    ACTION_STOP,
    ACTION_DESTROY,
    ACTION_DESTROY_VIEW,
    ACTION_ACTIVITY_DESTROY,
    ACTION_PAGE_LEAVE,
    ACTION_PAGE_RE_CREATED_VIEW,
    ACTION_PAGE_BACK
}